import { useEffect, useMemo, useState } from "react";
import { Link, NavLink, Route, Routes, useLocation, useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, ArrowRight, ChevronDown, Heart, Instagram, Menu, Minus, Plus, Search, ShoppingBag, User, X, ShieldCheck, Truck, RotateCcw, Leaf, Mail, MapPin, Phone, LogOut, Package, Users, Settings, LayoutDashboard, Boxes, UserPlus } from "lucide-react";
import { supabase } from "./lib/supabase";
import { collections, products, type Product } from "./data";

type CartItem = { product: Product; size: string; qty: number };
const money = (n:number) => new Intl.NumberFormat("ar-EG",{style:"currency",currency:"EGP",maximumFractionDigits:0}).format(n);

function App(){
  const [cart,setCart]=useState<CartItem[]>(()=>JSON.parse(localStorage.getItem("masar-cart")||"[]"));
  const [user,setUser]=useState<any>(null);
  useEffect(()=>{localStorage.setItem("masar-cart",JSON.stringify(cart))},[cart]);
  useEffect(()=>{ if(!supabase)return; supabase.auth.getSession().then(({data})=>setUser(data.session?.user??null)); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null)); return()=>data.subscription.unsubscribe()},[]);
  const add=(product:Product,size:string)=>setCart(c=>{const i=c.findIndex(x=>x.product.id===product.id&&x.size===size);if(i<0)return [...c,{product,size,qty:1}];const n=[...c];n[i]={...n[i],qty:n[i].qty+1};return n});
  const update=(id:string,size:string,d:number)=>setCart(c=>c.map(x=>x.product.id===id&&x.size===size?{...x,qty:Math.max(1,x.qty+d)}:x));
  const remove=(id:string,size:string)=>setCart(c=>c.filter(x=>!(x.product.id===id&&x.size===size)));
  const count=cart.reduce((s,x)=>s+x.qty,0);
  return <><TopBar/><Header count={count} user={user}/><Routes>
    <Route path="/" element={<Home/>}/><Route path="/collections" element={<Collections/>}/><Route path="/collections/:id" element={<Collection/>}/>
    <Route path="/product/:id" element={<ProductPage add={add}/>}/><Route path="/cart" element={<Cart cart={cart} update={update} remove={remove}/>}/>
    <Route path="/checkout" element={<Checkout cart={cart}/>}/><Route path="/contact" element={<Contact/>}/><Route path="/faq" element={<FAQ/>}/>
    <Route path="/shipping" element={<Policy title="سياسة الشحن" sections={[["مدة التجهيز","نقوم بتجهيز طلبك خلال يوم إلى يوم عمل من تأكيد الطلب واستلام الدفع. الطلبات المؤكدة قبل الساعة ٢ ظهرًا تُجهز في نفس اليوم عادة."],["خيارات التوصيل والتكلفة","الشحن مجاني للطلبات فوق ١٥٠٠ ج.م. وتطبق رسوم ثابتة على الطلبات الأقل حسب منطقة التوصيل."],["تتبع الطلب","بعد شحن طلبك، نرسل رقم التتبع عبر واتساب والبريد الإلكتروني لمتابعة طلبك لحظة بلحظة."],["المناطق غير المغطاة","إذا كانت منطقتك خارج نطاق التوصيل، سنتواصل معك لتنسيق بديل مناسب أو استرداد المبلغ بالكامل."]]}/>}
    <Route path="/returns" element={<Policy title="سياسة الإرجاع والاستبدال" sections={[["مدة الإرجاع","يمكنك طلب إرجاع أو استبدال المنتج خلال ١٤ يومًا من تاريخ الاستلام، بشرط أن يكون بحالته الأصلية ولم يتم ارتداؤه أو غسله."],["شروط الإرجاع","المنتج بحالته الأصلية مع جميع الملحقات والتغليف. المنتجات المخفضة قابلة للإرجاع فقط وليس الاستبدال. المنتجات ذات الطباعة المخصصة لا تُقبل للإرجاع إلا في حال وجود عيب تصنيع."],["عملية الإرجاع","تواصل معنا عبر صفحة اتصل بنا واذكر رقم الطلب وسبب الإرجاع. سيتولى فريقنا تنسيق الاستلام ومعالجة الطلب."],["استرداد المبلغ","يتم استرداد المبلغ على نفس وسيلة الدفع الأصلية خلال ٧ أيام عمل بعد استلام المنتج وفحصه."]]}/>}
    <Route path="/login" element={<Auth mode="login"/>}/><Route path="/signup" element={<Auth mode="signup"/>}/><Route path="/forgot-password" element={<Auth mode="forgot"/>}/><Route path="/reset-password" element={<Auth mode="reset"/>}/>
    <Route path="/account" element={<Account user={user}/>}/><Route path="/admin/*" element={<Admin user={user}/>}/>
    <Route path="*" element={<NotFound/>}/>
  </Routes><Footer/></>
}

function TopBar(){return <div className="topbar">شحن مجاني للطلبات فوق ١٥٠٠ ج.م <span>·</span> هدية مميزة من مسار مع طلبك 🎁</div>}
function Header({count,user}:{count:number,user:any}){const [open,setOpen]=useState(false);return <header className="header"><Link to="/" className="logo">مسار<span>MASAR</span></Link><nav className={open?"nav open":"nav"}><NavLink to="/">الرئيسية</NavLink><NavLink to="/collections">المجموعات</NavLink><NavLink to="/faq">الأسئلة الشائعة</NavLink><NavLink to="/contact">اتصل بنا</NavLink>{user?.user_metadata?.role==="owner"&&<NavLink to="/admin">لوحة التحكم</NavLink>}</nav><div className="actions"><Link to="/account" aria-label="الحساب"><User size={19}/></Link><Link to="/cart" className="cart-icon"><ShoppingBag size={20}/>{count>0&&<b>{count}</b>}</Link><button className="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>}

function Home(){return <main><section className="hero"><div className="hero-copy"><small>هوية تُلبس، لا مجرد ملابس</small><h1>مسار يصنع<br/>فرقًا في التفاصيل.</h1><p>ملابس رجالية مصممة بهدوء، بخامات نختارها بعناية وتفاصيل تعكس شخصيتك.</p><Link className="btn" to="/collections">اكتشف المجموعات <ArrowLeft size={17}/></Link></div></section><section className="story section"><div className="story-images"><img src={products[1].image}/><img src={products[0].image}/></div><div><eyebrow>من أين بدأنا</eyebrow><h2>وُلدت من فكرة بسيطة: أن التفاصيل تصنع الفارق</h2><p>مسار علامة مصرية تضع الجودة قبل الضجيج. نؤمن أن القطعة الجيدة لا تحتاج إلى مبالغة؛ تحتاج خامة ممتازة، قصة متوازنة وتفاصيل صادقة.</p><Link className="text-link" to="/collections">اكتشف المجموعات <ArrowLeft size={16}/></Link></div></section><Values/><section className="stats"><div><strong>+25</strong><span>منتج مميز</span></div><div><strong>4.8</strong><span>متوسط التقييم</span></div><div><strong>+1000</strong><span>عميل سعيد</span></div><div><strong>100%</strong><span>عناية بالتفاصيل</span></div></section><section className="cta"><div><h2>اكتشف هويتك القادمة</h2><p>قطع صُممت لتعيش معك، لا لتختفي مع الموضة.</p></div><Link className="btn light" to="/collections">تسوق الآن <ArrowLeft size={17}/></Link></section></main>}
function Values(){const v=[[ShieldCheck,"جودة قبل الضجيج","نختار الخامات بعناية ونراجع التفاصيل قبل وصول القطعة إليك."],[Leaf,"هوية بروح مصرية","تصميم حديث يحافظ على روح المكان بدون مبالغة."],[Boxes,"استدامة حقيقية","نصمم قطعًا تعيش أطول ونقلل الهدر قدر الإمكان."],[Heart,"تجربة تستاهل","من أول زيارة للموقع وحتى فتح طلبك، كل تفصيلة محسوبة."]];return <section className="values section"><eyebrow>ما الذي يؤمن به</eyebrow><h2>قيمنا الأساسية</h2><div className="value-grid">{v.map(([I,t,d])=><article><span className="icon"><I size={18}/></span><h3>{t as string}</h3><p>{d as string}</p></article>)}</div></section>}
function Collections(){return <main><PageHead kicker="مجموعات مختارة" title="المجموعات" text="كل مجموعة تحكي قصة مختلفة. استكشف تشكيلاتنا المنسقة بعناية واعثر على القطعة التي تكمل هويتك."/><section className="collection-grid section">{collections.map(c=><Link to={"/collections/"+c.id} className="collection-card"><img src={c.image}/><div><h2>{c.name}</h2><p>{c.subtitle}</p><span>اكتشف المجموعة <ArrowLeft size={15}/></span></div></Link>)}</section></main>}
function Collection(){const {id}=useParams();const c=collections.find(x=>x.id===id)||collections[0];const ps=products.filter(p=>p.collection===c.name);return <main><PageHead kicker="مجموعة مختارة" title={c.name} text={c.subtitle}/><section className="product-grid section">{(ps.length?ps:products).map(p=><ProductCard p={p}/>)}</section></main>}
function ProductCard({p}:{p:Product}){return <Link to={"/product/"+p.id} className="product-card"><div className="product-image"><img src={p.image}/><button onClick={e=>e.preventDefault()} aria-label="المفضلة"><Heart size={18}/></button></div><div className="product-meta"><div><h3>{p.name}</h3><span>{p.collection}</span></div><strong>{money(p.price)}</strong></div></Link>}
function ProductPage({add}:{add:(p:Product,s:string)=>void}){const {id}=useParams();const p=products.find(x=>x.id===id)||products[0];const [size,setSize]=useState(p.sizes[1]);return <main><section className="product-detail section"><div className="product-photo"><img src={p.image}/></div><div className="product-info"><eyebrow>{p.collection}</eyebrow><h1>{p.name}</h1><div className="price">{money(p.price)}</div><p>{p.description}</p><hr/><label>المقاس</label><div className="sizes">{p.sizes.map(s=><button className={size===s?"selected":""} onClick={()=>setSize(s)}>{s}</button>)}</div><button className="btn full" onClick={()=>add(p,size)}>أضف إلى السلة <ShoppingBag size={18}/></button><div className="trust-row"><span><Truck size={17}/> توصيل سريع</span><span><RotateCcw size={17}/> إرجاع خلال ١٤ يوم</span><span><ShieldCheck size={17}/> دفع آمن</span></div></div></section></main>}
function Cart({cart,update,remove}:{cart:CartItem[],update:(id:string,s:string,d:number)=>void,remove:(id:string,s:string)=>void}){const total=cart.reduce((s,x)=>s+x.product.price*x.qty,0);return <main><PageHead kicker="مراجعة طلبك" title="السلة" text="راجع اختياراتك قبل إتمام الطلب."/><section className="cart section">{!cart.length?<Empty title="سلتك فارغة" text="ابدأ باكتشاف المجموعات واختر القطع التي تناسبك."/>:<><div className="cart-list">{cart.map(x=><article className="cart-item"><img src={x.product.image}/><div><h3>{x.product.name}</h3><p>المقاس: {x.size}</p><strong>{money(x.product.price)}</strong><div className="qty"><button onClick={()=>update(x.product.id,x.size,-1)}><Minus/></button><span>{x.qty}</span><button onClick={()=>update(x.product.id,x.size,1)}><Plus/></button></div><button className="remove" onClick={()=>remove(x.product.id,x.size)}>حذف</button></div></article>)}</div><aside className="summary"><h2>ملخص الطلب</h2><div><span>المجموع الفرعي</span><strong>{money(total)}</strong></div><div><span>الشحن</span><strong>{total>=1500?"مجاني":"يحدد عند الدفع"}</strong></div><hr/><div className="grand"><span>الإجمالي</span><strong>{money(total)}</strong></div><div className="gift">🎁 <span>ستصلك هدية مميزة من مسار مع طلبك.</span></div><Link className="btn full" to="/checkout">إتمام الطلب <ArrowLeft size={17}/></Link></aside></>}</section></main>}
function Checkout({cart}:{cart:CartItem[]}){const [done,setDone]=useState(false);const [form,setForm]=useState({name:"",phone:"",email:"",address:"",city:"",payment:"cod"});const total=cart.reduce((s,x)=>s+x.product.price*x.qty,0);if(done)return <main><section className="success section"><div className="success-icon">✓</div><h1>تم استلام طلبك بنجاح</h1><p>شكرًا لاختيارك مسار. سنرسل لك تفاصيل الطلب وطرق المتابعة عبر بيانات التواصل.</p><div className="gift big">🎁 <span>ومع طلبك، ستصلك هدية مميزة من مسار.</span></div><Link className="btn" to="/">العودة للرئيسية</Link></section></main>;return <main><PageHead kicker="آخر خطوة" title="إتمام الطلب" text="أدخل بيانات التوصيل واختر طريقة الدفع المناسبة."/><section className="checkout section"><form onSubmit={e=>{e.preventDefault();setDone(true)}}><h2>بيانات التوصيل</h2><div className="form-grid">{(["name","phone","email","city","address"] as const).map(k=><label>{({name:"الاسم الكامل",phone:"رقم الهاتف",email:"البريد الإلكتروني",city:"المحافظة",address:"العنوان بالتفصيل"} as any)[k]}<input required value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><h2>طريقة الدفع</h2><div className="payments"><label><input type="radio" checked={form.payment==="cod"} onChange={()=>setForm({...form,payment:"cod"})}/> الدفع عند الاستلام</label><label><input type="radio" checked={form.payment==="bank"} onChange={()=>setForm({...form,payment:"bank"})}/> تحويل بنكي / دفع إلكتروني</label></div><button className="btn full">تأكيد الطلب <ArrowLeft size={17}/></button></form><aside className="summary"><h2>ملخص الطلب</h2>{cart.map(x=><div><span>{x.product.name} × {x.qty}</span><strong>{money(x.product.price*x.qty)}</strong></div>)}<hr/><div className="grand"><span>الإجمالي</span><strong>{money(total)}</strong></div><div className="gift">🎁 <span>هدية مميزة من مسار مع طلبك</span></div></aside></section></main>}
function Auth({mode}:{mode:"login"|"signup"|"forgot"|"reset"}){const nav=useNavigate();const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [name,setName]=useState("");const [msg,setMsg]=useState("");const title={login:"تسجيل الدخول",signup:"إنشاء حساب",forgot:"استعادة كلمة المرور",reset:"إعادة تعيين كلمة المرور"}[mode];const submit=async(e:any)=>{e.preventDefault();if(!supabase){setMsg("اربط Supabase أولًا من خلال متغيرات البيئة.");return}let r:any;if(mode==="login")r=await supabase.auth.signInWithPassword({email,password});if(mode==="signup")r=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});if(mode==="forgot")r=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin+"/reset-password"});if(mode==="reset")r=await supabase.auth.updateUser({password});setMsg(r?.error?.message||"تمت العملية بنجاح");if(!r?.error&&mode==="login")nav("/")};return <main><section className="auth"><div className="auth-card"><eyebrow>حساب مسار</eyebrow><h1>{title}</h1><p>{mode==="login"?"مرحبًا بعودتك.":"أدخل بياناتك لإكمال العملية."}</p><form onSubmit={submit}>{mode==="signup"&&<input required placeholder="الاسم الكامل" value={name} onChange={e=>setName(e.target.value)}/>}<input required type="email" placeholder="البريد الإلكتروني" value={email} onChange={e=>setEmail(e.target.value)}/>{mode!=="forgot"&&<input required type="password" placeholder="كلمة المرور" value={password} onChange={e=>setPassword(e.target.value)}/>}<button className="btn full">{title}</button></form>{msg&&<div className="notice">{msg}</div>}{mode==="login"&&<><Link to="/forgot-password">نسيت كلمة المرور؟</Link><p>ليس لديك حساب؟ <Link to="/signup">إنشاء حساب</Link></p></>}{mode==="signup"&&<p>لديك حساب؟ <Link to="/login">تسجيل الدخول</Link></p>}{mode==="forgot"&&<p><Link to="/login">العودة لتسجيل الدخول</Link></p>}</div></section></main>}
function Account({user}:{user:any}){const nav=useNavigate();return <main><PageHead kicker="حسابك" title="حساب مسار" text={user?"إدارة بياناتك وطلباتك السابقة.":"سجل الدخول لمتابعة طلباتك وإدارة حسابك."}/><section className="section account">{user?<><div className="account-card"><User/><div><h2>{user.user_metadata?.full_name||"عميل مسار"}</h2><p>{user.email}</p></div><button onClick={async()=>{await supabase?.auth.signOut();nav("/")}}><LogOut size={17}/> تسجيل الخروج</button></div><div className="account-card"><Package/><div><h3>طلباتي</h3><p>ستظهر هنا الطلبات المرتبطة بحسابك.</p></div></div></>:<Link className="btn" to="/login">تسجيل الدخول</Link>}</section></main>}
function Admin({user}:{user:any}){const [tab,setTab]=useState("dashboard");if(!user)return <NavigateLogin/>;const items=[["dashboard","نظرة عامة",LayoutDashboard],["orders","الطلبات",Package],["products","المنتجات",Boxes],["customers","العملاء",Users],["admins","المدراء",UserPlus],["settings","الإعدادات",Settings]] as const;return <main className="admin"><aside>{items.map(([k,t,I])=><button className={tab===k?"active":""} onClick={()=>setTab(k)}><I size={18}/>{t}</button>)}</aside><section className="admin-content"><div className="admin-head"><div><eyebrow>لوحة التحكم</eyebrow><h1>{items.find(x=>x[0]===tab)?.[1]}</h1></div><Link className="text-link" to="/">زيارة المتجر <ArrowLeft/></Link></div>{tab==="dashboard"&&<Dashboard/>}{tab==="orders"&&<AdminOrders/>}{tab==="products"&&<AdminProducts/>}{tab==="customers"&&<AdminCustomers/>}{tab==="admins"&&<AdminAdmins/>}{tab==="settings"&&<AdminSettings/>}</section></main>}
function Dashboard(){return <div className="admin-grid"><Stat title="إجمالي الطلبات" value="0"/><Stat title="مبيعات اليوم" value="0 ج.م"/><Stat title="عملاء" value="0"/><Stat title="منتجات" value={String(products.length)}/><div className="admin-panel wide"><h2>آخر الطلبات</h2><Empty title="لا توجد طلبات بعد" text="ستظهر الطلبات الجديدة هنا فور وصولها."/></div></div>}
function Stat({title,value}:{title:string,value:string}){return <article className="stat-card"><span>{title}</span><strong>{value}</strong></article>}
function AdminOrders(){return <div className="admin-panel"><h2>إدارة الطلبات</h2><p>تابع الطلبات وغيّر حالتها من مؤكد إلى جاهز للشحن ثم تم الشحن والتسليم أو الإلغاء.</p><Empty title="لا توجد طلبات" text="الطلبات الجديدة ستظهر هنا."/></div>}
function AdminProducts(){return <div className="admin-panel"><div className="panel-head"><h2>إدارة المنتجات</h2><button className="btn small">إضافة منتج</button></div>{products.map(p=><div className="admin-row"><img src={p.image}/><div><b>{p.name}</b><span>{p.collection}</span></div><strong>{money(p.price)}</strong><span>{p.stock} قطعة</span><button>تعديل</button></div>)}</div>}
function AdminCustomers(){return <div className="admin-panel"><h2>العملاء</h2><Empty title="لا يوجد عملاء" text="سيظهر العملاء المسجلون وملخص طلباتهم هنا."/></div>}
function AdminAdmins(){return <div className="admin-panel"><div className="panel-head"><div><h2>مدراء المنصة</h2><p>إضافة وإدارة حسابات فريق الإدارة.</p></div><button className="btn small">إضافة أدمن</button></div><div className="notice">صلاحية <b>Owner</b> مخصصة للحساب الرئيسي فقط. لا يمكن للأدمن العادي رفع صلاحياته أو تعديل حساب الـ Owner.</div></div>}
function AdminSettings(){return <div className="admin-panel"><h2>إعدادات المتجر</h2><div className="form-grid"><label>اسم المتجر<input value="مسار | MASAR" readOnly/></label><label>البريد<input value="support@masar.com" readOnly/></label><label>الشحن المجاني من<input value="1500" readOnly/></label><label>هدية الطلب<input value="هدية مميزة من مسار" readOnly/></label></div></div>}
function NavigateLogin(){return <section className="auth"><div className="auth-card"><h1>تسجيل الدخول مطلوب</h1><Link className="btn" to="/login">تسجيل الدخول</Link></div></section>}
function Policy({title,sections}:{title:string,sections:string[][]}){return <main><PageHead kicker="المعلومات" title={title} text="نوضح لك كل ما تحتاج معرفته قبل وبعد طلبك."/><section className="policy section">{sections.map(([h,d])=><article><h2>{h}</h2><p>{d}</p></article>)}</section></main>}
function FAQ(){const qs=["ما هي طرق الدفع المتاحة؟","كم تستغرق مدة التوصيل؟","هل يمكنني إرجاع أو استبدال المنتج؟","كيف أعرف مقاسي الصحيح؟","هل توجد خصومات أو أكواد متاحة؟","كيف أتتبع طلبي؟","هل توفرون خارج مصر؟","ما هي سياسة استرداد الأموال؟"];const [open,setOpen]=useState(0);return <main><PageHead kicker="الدعم" title="الأسئلة الشائعة" text="جمعنا لك إجابات أكثر الأسئلة تكرارًا. لم تجد ما تبحث عنه؟ تواصل معنا وسنساعدك."/><section className="faq section">{qs.map((q,i)=><article className={open===i?"open":""} onClick={()=>setOpen(open===i?-1:i)}><div><b>{q}</b><ChevronDown/></div>{open===i&&<p>{i===0?"نوفر الدفع عند الاستلام، وخيارات الدفع الإلكتروني والتحويل البنكي حسب المتاح عند إتمام الطلب.":i===1?"عادة يصل الطلب داخل القاهرة خلال 2–4 أيام عمل وباقي المحافظات خلال 3–6 أيام عمل.":i===2?"نعم، وفق شروط سياسة الإرجاع والاستبدال خلال 14 يومًا من الاستلام.":"إذا كان سؤالك مختلفًا، تواصل معنا من صفحة اتصل بنا وسيساعدك فريق مسار."}</p>}</article>)}</section></main>}
function Contact(){return <main><PageHead kicker="نحن هنا لمساعدتك" title="اتصل بنا" text="سواء كان لديك سؤال عن مقاس، طلب، أو تعاون تجاري، فريقنا جاهز للرد عليك."/><section className="contact section"><form className="contact-form"><div className="form-grid"><input placeholder="الاسم الكامل"/><input placeholder="البريد الإلكتروني"/><input placeholder="رقم الهاتف"/><input placeholder="الموضوع"/></div><textarea placeholder="اكتب رسالتك هنا..."/><button className="btn full">إرسال الرسالة</button></form><div className="contact-cards"><Info icon={Phone} title="واتساب" text="+20 100 000 0000"/><Info icon={Mail} title="البريد الإلكتروني" text="support@masar.com"/><Info icon={MapPin} title="العنوان" text="القاهرة، مصر"/></div></section></main>}
function Info({icon:I,title,text}:{icon:any,title:string,text:string}){return <article><span className="icon"><I size={20}/></span><div><small>{title}</small><b>{text}</b></div></article>}
function PageHead({kicker,title,text}:{kicker:string,title:string,text:string}){return <section className="page-head"><div><eyebrow>{kicker}</eyebrow><h1>{title}</h1><p>{text}</p></div></section>}
function Empty({title,text}:{title:string,text:string}){return <div className="empty"><ShoppingBag size={28}/><h3>{title}</h3><p>{text}</p></div>}
function NotFound(){return <main><section className="success section"><h1>الصفحة غير موجودة</h1><Link className="btn" to="/">العودة للرئيسية</Link></section></main>}
function Footer(){return <footer><div><Link className="logo" to="/">مسار<span>MASAR</span></Link><p>نصنع قطعًا هادئة بهوية واضحة وتفاصيل تستحق.</p><div className="social"><Instagram size={17}/></div></div><div><b>المتجر</b><Link to="/collections">المجموعات</Link><Link to="/faq">الأسئلة الشائعة</Link><Link to="/shipping">الشحن والتوصيل</Link></div><div><b>المساعدة</b><Link to="/returns">الإرجاع والاستبدال</Link><Link to="/contact">اتصل بنا</Link><Link to="/account">حسابي</Link></div><div><b>اشترك في نشرتنا</b><p>عروض وإطلاقات جديدة تصل إلى بريدك.</p><input placeholder="بريدك الإلكتروني"/><button className="btn small">اشتراك</button></div><div className="copyright">© 2026 مسار. جميع الحقوق محفوظة.</div></footer>}

export default App;